### ISSUE TITLE
Embulk v0.9.7 can't parse milliseconds part in `%s.%N` and `%s.%L` format.

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk#1033]
Reported by [ntrgiang](https://github.com/embulk/embulk/issues/467#issuecomment-416636390)

Embulk v0.9.7 can't parse milliseconds part in `%s.%N` and `%s.%L` format.
Embulk v0.8.39 can parse it. 

[Reporduce code](https://github.com/hiroyuki-sato/embulk-support/tree/master/core_467_timestamp_format/ntrgiang)

```
2018-08-29 19:05:16.852 +0900: Embulk v0.8.39
+-----------------+-----------------------------+------------+-------------+
| key_name:string |               day:timestamp | value:long | name:string |
+-----------------+-----------------------------+------------+-------------+
|   2 new_clients | 2018-04-06 11:06:02.001 UTC |          1 |           a |
|   3 new_clients | 2018-04-06 11:06:03.001 UTC |          2 |           b |
|   4 new_clients | 2018-04-06 11:06:04.001 UTC |          3 |           c |
+-----------------+-----------------------------+------------+-------------+
```

```
2018-08-29 19:05:50.172 +0900: Embulk v0.9.7
+-----------------+-------------------------+------------+-------------+
| key_name:string |           day:timestamp | value:long | name:string |
+-----------------+-------------------------+------------+-------------+
|   2 new_clients | 2018-04-06 11:06:02 UTC |          1 |           a |
|   3 new_clients | 2018-04-06 11:06:03 UTC |          2 |           b |
|   4 new_clients | 2018-04-06 11:06:04 UTC |          3 |           c |
+-----------------+-------------------------+------------+-------------+
```

**Comment by kamatama41** [comment]
When `%s` is specified,  `instantSeconds` is set as seconds since epoch, 
https://github.com/embulk/embulk/blob/e85d6998d139f65c79bc209207257f410d4e0db9/embulk-core/src/main/java/org/embulk/spi/time/RubyTimeParser.java#L297-L308
so that the following `if` block is available, thus milliseconds set by `%N` or `%L` is ignored.
https://github.com/embulk/embulk/blob/e85d6998d139f65c79bc209207257f410d4e0db9/embulk-core/src/main/java/org/embulk/spi/time/RubyTimeParsed.java#L645-L660

As these syntaxes work in Ruby, I think it's a bug.
```ruby
irb(main):046:0> Time.strptime("1523012762.001", "%s.%L").strftime("%Y-%M-%d %H:%M:%S.%L")
=> "2018-06-06 04:06:02.001"
irb(main):048:0> Time.strptime("1523012762.001", "%s.%N").strftime("%Y-%M-%d %H:%M:%S.%N")
=> "2018-06-06 04:06:02.001000000"
```

@dmikurube 
What do you think?

**Comment by dmikurube** [comment]
@hiroyuki-sato @kamatama41 Thanks for your detailed investigation and reports. Hmm, I remembered I intentionally did it for `%Q %N`, but I don't remember I've considered `%s %N` at the same time. :(

I'll have a deeper look, and have the right fix.

**Comment by dmikurube** [comment]
Hmmmm, the experimental code in the comment:

```
     // irb(main):002:0> Time.strptime("123456789 12.345", "%Q %S.%N").nsec 
     // => 789000000 
```

shows a different result when I confirmed just now.

```
irb(main):002:0> Time.strptime("123456789 12.345", "%Q %S.%N").nsec
=> 134000000
```

It's the same in Ruby versions 2.2, 2.3, 2.5, and some versions of JRuby. I'm confused, but I might have missed something this time or when I wrote the comment... The current Embulk implementation might be based on the former one (`789000000`), but we're now looking in the latter one (`134000000`).

Let me investigate the cause at first. Fix would come later...

**Comment by dmikurube** [comment]
From [a hint from our colleague](https://twitter.com/nalsh/status/1035666075008921600), it turned out that the behavior was different per Ruby version.

It might or might not be the reason of the misunderstanding. But anyways, we'd basically want to follow Embulk 0.8's behavior, and the latest Ruby's behavior as well. Will fix it.

```
Time.strptime("123456789 12.345", "%Q %S.%N").nsec
=>

ruby-1.9.0-0          345000000
...
ruby-1.9.3-rc1
ruby-1.9.3-p0         789000000
...
ruby-2.1.6
ruby-2.1.7            134000000
...
ruby-2.1.10
ruby-2.2.0-preview1   789000000
...
ruby-2.2.2
ruby-2.2.3            134000000
...
```
