### ISSUE TITLE
Why does Page Scattering create multiple output files?

### ISSUE THREAD

**Issue by matochondrion** [embulk/embulk#1138]
Hello,

I'm curious about about the concept of "page scattering" and setting
`min_out_tasks` to 1 in order to prevent multiple output files from being
creating.

My team wants to work with a single ouput file, so we are tempted to set
`min_out_tasks` to `1` otherwise we have to work with multiple output files.

However we're uncertain about what the consequences are
of doing this?  Are we reducing the Embulk's performance if we limit the tasks
to 1? Or is there some other consequence I'm not considering?

Thank you!

**Comment by dmikurube** [comment]
It runs on several threads like :

* Thread 1: [input] => [filters] => [output]
* Thread 2: [input] => [filters] => [output]
* ...

Then it's natural that multiple files are created. Otherwise, it has to serialize it to one file, and it kills the benefits of multithreads. It's the nature of Embulk, and multithreads.

Yes, `min_out_tasks: 1` makes a single output, but of course, you're killing the benefits of multithreads.

**Comment by matochondrion** [comment]
Thank you for the explanation!
