### ISSUE TITLE
Fix gemspec template

### ISSUE THREAD

**Issue by naoty** [embulk/embulk#1166]
On OS without git, `embulk new ruby-input test` prints following output.

```rb

Gem::Specification.new do |spec|
  spec.name          = "embulk-input-test"
  spec.version       = "0.1.0"
  spec.authors       = ["YOUR_NAME"]
  spec.summary       = "Test input plugin for Embulk"
  spec.description   = "Loads records from Test."
  spec.email         = ["YOUR_NAME"]
  spec.licenses      = ["MIT"]
  # TODO set this: spec.homepage      = "https://github.com/YOUR_NAME/embulk-input-test"

  spec.files         = `git ls-files`.split("\n") + Dir["classpath/*.jar"]
  spec.test_files    = spec.files.grep(%r{^(test|spec)/})
  spec.require_paths = ["lib"]

  #spec.add_dependency 'YOUR_GEM_DEPENDENCY', ['~> YOUR_GEM_DEPENDENCY_VERSION']
  spec.add_development_dependency 'embulk', ['>= 0.9.18-SNAPSHOT']
  spec.add_development_dependency 'bundler', ['>= 1.10.6']
  spec.add_development_dependency 'rake', ['>= 10.0']
end
```

* Default value for `spec.email` should be `YOUR_EMAIL` instead of `YOUR_NAME`.
* Unnecessary empty line is present at top of gemfile.
* Single quotes or double quotes should be used throughout gemspec.

**Comment by dmikurube** [comment]
Thanks for filing the issue. We'll be moving the "new plugin template" feature to our Gradle plugin. Things will be fixed (renewed) there.

https://github.com/embulk/gradle-embulk-plugins

**Comment by naoty** [comment]
@dmikurube This plugin is shipped with latest embulk? If this plugin isn't shipped soon, would you merge this PR?

**Comment by dmikurube** [comment]
Planned to ship the Gradle plugin with the "new template feature" not very soon (we're on the way), but unless it is causing a serious problem on use-case, we have no intention to touch this part in `embulk-core` until it is removed so that it won't affect any. Sorry about that.

Anyways, although the Gradle plugin with the "new template feature" is not very soon, its v0.2.1 will be released soon, and it makes this `gemspec` unnecessary. This `gemspec` fix won't be needed then.
