### ISSUE TITLE
[Feature Request] Support timestamp in json data type

### ISSUE THREAD

**Issue by sonots** [embulk/embulk#417]
I think what users (including me) want is a kind of recursive data type, not `JSON` in fact.

See bigquery data type. https://cloud.google.com/bigquery/preparing-data-for-bigquery#datatypes. 
BigQuery has `STRING`, `BYTES`, `INTEGER`, `FLOAT`, `BOOLEAN`, `TIMESTAMP`, and `RECORD` (a kind of recursive data type). `RECORD` can have `STRING`, `BYTES`, `INTEGER`, `FLOAT`, `BOOLEAN`, `TIMESTAMP`, and `RECORD` inside.

Embulk has `string`, `long`, `double`, `boolean`, `timestamp`, and `json` type. However, `json` type can have only `string`, `long`, `double`, `boolean`, and `json` inside. `timestamp` is not supported.

PS. I think the name, `json` will be not appropriate if it supports `timestamp`, though.

**Comment by frsyuki** [comment]
@sonots I chose `json` because many storage systems or SaaS services use JSON as the primary format of schema-less values. Such as postgresql, mysql, treasure data, etc. It's good for output plugins because output plugins don't need confusing conversion.
If we include timestamp, output plugins need to convert timestamp to a json value (string in ISO 8601 timestamp format, integer in UNIX timestamp, etc.).

Question here is:

* what's the use case to include timestamp in json type? why do you want it?
* what approach do you think the most straightforward if a storage supports json but doesn't support timestamp in json?
* when output plugin formats json type to a string (like CSV formatter), what approach do you think the easiest to understand? I think default can be ISO 8601 extended timestamp format with optional nano seconds but should it be configurable?

**Comment by sonots** [comment]
> @sonots I chose json because many storage systems or SaaS services use JSON as the primary format of schema-less values. Such as postgresql, mysql, treasure data, etc. 

Nowadays, there are several storages which accept json for **schema-full** values such as bigquery, vertica.

> what's the use case to include timestamp in json type? why do you want it?

Currently, with filter plugin, if we want to treat a column inside a json object as a timestamp, we convert string or unixtimestamp into timestamp object, and then we have to convert it back to string or unixtimestamp because json type does not allow timestamp object. This is apparently less efficient.

And , finally we want to format the timestamp column to be appropriate for output storages.

> what approach do you think the most straightforward if a storage supports json but doesn't support timestamp in json?

Convert into a string

> when output plugin formats json type to a string (like CSV formatter), what approach do you think the easiest to understand? I think default can be ISO 8601 extended timestamp format with optional nano seconds but should it be configurable?

BigQuery

https://cloud.google.com/bigquery/preparing-data-for-bigquery#datatypes

2014-08-19 07:41:35.220 -05:00
2014-08-19 12:41:35.220 UTC
2014-08-19 12:41:35.220
2014-08-19 12:41:35.220000
2014-08-19T12:41:35.220Z

and unixtimestamp with microsec precision

PostgreSQL

http://www.postgresql.org/docs/9.1/static/datatype-datetime.html

iso8601

Vertica

Should be similar with PostgreSQL.

https://my.vertica.com/docs/7.1.x/HTML/Content/Authoring/SQLReferenceManual/DataTypes/Date-Time/TIMESTAMP.htm

1999-01-08 04:05:06
1999-01-08 04:05:06 -8:00
January 8 04:05:06 1999 PST

MySQL

http://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html#function_get-format

> DATE_FORMAT()function description). ISO format refers to ISO 9075, not ISO 8601.
it seems iso8601 is not acceptable.

I think the default format can be the same with the current timestamp object since I am considering the "json" type as a recursive data type. It should be simpler. Timestamp format must be configurable.

**Comment by frsyuki** [comment]
> Nowadays, there are several storages which accept json for schema-full values such as bigquery, vertica.

Embulk's assumption is that you use schema-full columns instead of a single `json` column. Is the reason why you don't take that way because you have a schema-less data source? Why do you need schema-less input? Schema-less input + schema-full output is something I didn't expect when I added JSON type. My assumption was that input should be schema-full (or a filter plugin converts types to enforce schema) if output is schema-full. Otherwise, both input and output are schema-less and it can use JSON.

If your concern is about reusability of config file (you don't want to include schema information of the data source in config file), #242 is a plan to solve it. A guess plugins for output plugins will be able to add a filter plugin that converts a json column to schema-full columns based on metadata taken from the destination. For example, `embulk guess -g bigquery-expand-json seed.yml` (command name of "guess" could be different like "complete") gets table schema from bigquery first, then generates a filter plugin that converts a json column to schema-full columns.

With this way, output plugin can control conversion behavior from input schema to destination schema flexibly including timestamp format like embulk-output-jdbc's column_options. Output plugins don't need additional options/code to convert json to schema-full columns because the generated filter plugin does it.

Or is a timestamp value in a nested field?

> This is apparently less efficient.

Current timestamp parser is stupidly super slow. Did you try java_time_parser_v2 branch? It improves performance significantly.

**Comment by sonots** [comment]
BigQuery supports a timestamp column in a nested field. This example motivates me much because I recently am working to bulkload into BigQuery.

**Comment by sonots** [comment]
Vertica also supports a timestamp in a nested field with fjsonparser (actually, the column name becomes like nested.time, though). Some of analysts say as they want to load like this because it makes easier to use data for thier analysis.

**Comment by sonots** [comment]
> Schema-less input + schema-full output is something I didn't expect

Log evolves everyday, so I have to consider the case "schema-less input + schema-full output". 
An engineer developing a service often use a json payload for extensibility.

But, an analyst may want to take the new field as an individual column because it makes easier to write a query, and makes faster because some storage does not support index in json column.

Output schema can be varying in rapid growing stage, but still schema-full. My job is to support such requests of analysts.

**Comment by dmikurube** [comment]
This isn't simply to be done in v0.9.0 very soon. To be considered in later versions.

**Comment by dmikurube** [comment]
I don't think it would happen. Let's close it.
