### ISSUE TITLE
CSV parser always converts a non-quoted empty string to null regardless of `null_string`

### ISSUE THREAD

**Issue by sonots** [embulk/embulk#433]
Discussion continued from https://github.com/embulk/embulk/pull/432.

Currently, there is no way not to convert a non-quoted emtpy string to null.
Even if we specify `null_stirng: "NULL"` or something else, a non-quoted emtpy string is always converted into null. We need an option to keep a non-quoted empty string as an empty string.

**Comment by sonots** [comment]
> CSV parser plugin converts a non-quoted empty string to null but quoted empty string is kept an empty string. 

Keeping this default behavior is fine.

**Comment by frsyuki** [comment]
> Keeping this default behavior is fine, and this behavior must be written on the document 
Sounds good. Let's take these ways.

**Comment by sonots** [comment]
Thanks. And. my problem is not for the default behavior. The problem appears when we specify `null_stirng: "NULL"` or something. It still converts a non-quoted empty string to null.

**Comment by frsyuki** [comment]
ok. it was unclear from the PR that changes the default behavior.
I think the easiest implementation is to change the meaning of `null_string:` option so that default behavior (`null_string: null`) makes non-quoted strings to NULL, setting empty string (`null_string: ""`) makes any empty strings to NULL regardless of quotation, and setting other strings (`null_strings: abc`) makes the string to NULL regardless of quotation.

**Comment by sonots** [comment]
Agree with the specification. I will resend PR.

> ok. it was unclear from the PR that changes the default behavior.

yep, I mistakenly changed the default behavior with #432 because I did not know `CSV parser plugin converts a non-quoted empty string to null but quoted empty string is kept an empty string.` was its specification.
