### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by kakoni** [embulk/embulk#495]
When running embulk with --log parameter output is bit inconsistent(especially when running embulk with crontab where I'm trying to avoid unnecessary output).
So what happens currently

1) In errorless run
- Embulk version (Embulk v0.8.14) is printed to stdout, everything else goes to --log file

2) Errorfull run
- Embulk version is printed to stdout
- Actual error message/stacktrace in printed to stdout
- Everything else goes to --log file

**Comment by hiroyuki-sato** [comment]
The following `2016-10-28 22:10:20.281 +0900: Embulk v0.8.14` part is the output before setup 
logger.

The first version output is the co-developer policy.
It is because of the following reason.

* JRuby setup is very slow. This output is the sign `Embulk working...`
* We want to know version number when someone asks questions.

```
embulk run --log /dev/null config.yml
2016-10-28 22:10:20.281 +0900: Embulk v0.8.14
```

Please redirect to `/dev/null` like the following
`embulk run --log /dev/null config.yml > /dev/null`

**Comment by kakoni** [comment]
Ok. So this an feature. Closing
