### ISSUE TITLE
Is there any features to get number of input records from output plugin?

### ISSUE THREAD

**Issue by noissefnoc** [embulk/embulk#517]
I'm writing embulk output plugin with Java and I want to know data is 0 records or not from output plugin. I think this feature prevents some undesirable cases for example create empty file on remote storage. Is there any related features? (This issue may be related issue #411 ?)

**Comment by hiroyuki-sato** [comment]
Just FYI.
The #501  is the similar issue. (Maybe it doesn't your expected feature)

**Comment by muga** [comment]
Not related features yet. Since output tasks are executed in parallel, it's not easy to avoid remote empty files if output tasks create each remote files. Your plugin could use TaskReports and know 0 records or not, if it would create remote files when the Embulk transaction finishes, it means, after control.run was invoked but.

**Comment by noissefnoc** [comment]
I understand. Thanks @hiroyuki-sato @muga
