### ISSUE TITLE
Provide general-purpose config units on embulk/embulk-plugin-units.git

### ISSUE THREAD

**Issue by muga** [embulk/embulk#595]
To provide a set of general-purpose config units as libraries would be helpful for Embulk plugin developers. Reusing such config units enables keeping plugins' source code compact. For example, HttpProxy (https://github.com/embulk/embulk-input-s3/pull/48) and TimestampParam (https://github.com/embulk/embulk/pull/465) config units can be reused by several input/output plugins.

These config units' repo should be separated from embulk/embulk.git by several reasons:
- They are different release cycle with Embulk itself. 
- Their version could be managed by each plugin. Input and output plugins can use different version of them.

**Comment by dmikurube** [comment]
As chatted f2f, I'd personally suggest to follow existing library naming conventions like:
* https://github.com/embulk/embulk-input-s3/tree/master/embulk-util-aws-credentials
* https://github.com/embulk/embulk-base-restclient/tree/master/embulk-util-retryhelper-jaxrs
* (embulk-base-restclient is `base` because it is not just a util, but a base classes of plugins.)

How about `embulk-util-config-units` or `-types`? (`-types` sounds more straightforward to me, imho.)

**Comment by muga** [comment]
Sounds good. What do you think `embulk-util-config`? In this case, the package name is `org.embulk.util.config`.

**Comment by dmikurube** [comment]
Looks good. The library may contain more than types in the future. :)

**Comment by muga** [comment]
Created https://github.com/embulk/embulk-util-config

I'm closing this.
